# Generated by Django 5.2.9 on 2025-12-16 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('rut', models.CharField(max_length=20)),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=200)),
                ('anios_experiencia', models.CharField(max_length=3)),
                ('calificacion', models.CharField(max_length=10)),
                ('activo', models.CharField(default='si', max_length=10)),
            ],
        ),
    ]
